services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo