services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - mongo
  reservations:
    image: us-east4-docker.pkg.dev/sleepr-378423/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: us-east4-docker.pkg.dev/sleepr-378423/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  mongo:
    image: mongo