services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - mongo
  reservations:
    image: nestjs-solid-octo-engine-reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: nestjs-solid-octo-engine-auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  mongo:
    image: mongo